project_id = "jstzgqmqwcjtffefwcxj"

 [functions.validate-voucher]
 verify_jwt = false
 
 [functions.get-available-vouchers]
 verify_jwt = false
 
[functions.send-notification]
verify_jwt = false

[functions.create-tokopay-payment]
verify_jwt = false

[functions.tokopay-callback]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false